const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'../outputs/harbor-bid/dist');
const source=['catalog.js','all-items.js','electronics-atlases.js','container-art.js','item-images.js','loot.js','loans.js','grid.js'].map(name=>fs.readFileSync(path.join(root,name),'utf8')).join('\n');
function load(saved=new Map()){
 const listeners={},nodes=new Map(),document={getElementById:id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',innerHTML:'',showModal(){},close(){}});return nodes.get(id);},querySelectorAll:()=>[],addEventListener:(type,fn)=>(listeners[type]||=[]).push(fn)};
 const ctx=vm.createContext({console,document,localStorage:{getItem:key=>saved.get(key)||null,setItem:(key,value)=>saved.set(key,value)}});vm.runInContext(source,ctx);
 return {ctx,saved,run:code=>vm.runInContext(code,ctx),click:(id,dataset={})=>{for(const fn of listeners.click||[])fn({target:{closest:()=>({id,dataset,disabled:false})}});}};
}

for(const amount of [1000000,3000000,6000000]){const c=load();assert(c.run('borrowLoan('+amount+')'));assert.equal(c.run('s.cash'),3000000+amount);assert(!c.run('borrowLoan(1000000)'));c.run('persist()');const next=load(c.saved);assert.equal(next.run('s.loan.balance'),amount);assert.equal(next.run('s.cash'),3000000+amount);}
assert(!load().run('borrowLoan(2000000)'));
function fixture(costOffset){const c=load();c.run(`borrowLoan(1000000);const originals=catalog.filter(it=>it.referencePrice<200000).slice(0,12);s.stock=originals.map((it,i)=>({...it,value:it.referencePrice,grade:it.fixedGrade,uid:'test-'+i,record:'test-box',revealed:true}));const gross=s.stock.reduce((sum,it)=>sum+it.value,0);s.records=[{id:'test-box',name:'测试箱',cost:gross-(${costOffset}),revenue:0,total:12,sold:0,confirmedValue:null,profitRepaymentBase:0}];s.current={...cargoTypes[0],id:'test-box',items:s.stock.map(it=>({...it}))};confirmCargoProfit(s.current);`);return c;}
const outcomes=[];
for(const profit of [-100001,0,500001])for(const mode of ['single','cargo','warehouse']){
 const c=fixture(profit),gross=c.run('s.stock.reduce((sum,it)=>sum+it.value,0)'),paid=Math.floor(Math.max(0,profit)*3/10);
 if(mode==='single')for(let i=0;i<12;i++)c.click('',{sellItem:'test-'+i});else c.click(mode==='cargo'?'sellCargo':'sellAllStock');
 assert.equal(c.run('s.cash'),4000000+gross-paid);assert.equal(c.run('s.loan.balance'),1000000-paid);assert.equal(c.run('s.records[0].repaid'),paid);assert.equal(c.run('s.records[0].revenue'),gross);assert.equal(c.run('s.stock.length'),0);
 const before=c.run('s.cash');c.click('sellAllStock');assert.equal(c.run('s.cash'),before);c.run('confirmCargoProfit(s.current)');assert.equal(c.run('s.cash'),before);
 c.run('persist()');const reloaded=load(c.saved);assert.equal(reloaded.run('s.loan.balance'),1000000-paid);assert.equal(reloaded.run('s.loan.remainder'),c.run('s.loan.remainder'));outcomes.push({mode,profit,gross,paid});
}
const partial=fixture(500001);partial.run('const cost=s.records[0].cost;');
for(let i=0;i<12;i++){const earned=partial.run('s.records[0].revenue'),value=partial.run('s.stock[0].value'),cost=partial.run('cost'),oldRepaid=partial.run('s.loan.repaid');partial.click('',{sellItem:'test-'+i});assert.equal(partial.run('s.loan.repaid'),Math.floor(Math.max(0,earned+value-cost)*3/10));if(earned+value<=cost)assert.equal(partial.run('s.loan.repaid'),oldRepaid);}
const deferred=fixture(500001);deferred.run('s.records[0].confirmedValue=null;s.current.items[11].revealed=false;const last=s.stock.pop();');deferred.click('sellAllStock');assert.equal(deferred.run('s.loan.repaid'),0);const priorCash=deferred.run('s.cash'),priorRevenue=deferred.run('s.records[0].revenue'),cost=deferred.run('s.records[0].cost');deferred.run('revealGrid(11)');const confirmedPaid=Math.floor(Math.max(0,priorRevenue-cost)*3/10);assert.equal(deferred.run('s.loan.repaid'),confirmedPaid);assert.equal(deferred.run('s.cash'),priorCash-confirmedPaid);deferred.click('sellAllStock');assert.equal(deferred.run('s.loan.repaid'),150000);
const batchReveal=fixture(500001);batchReveal.run('s.stock=[];s.current.items.forEach(it=>it.revealed=false);s.records[0].confirmedValue=null;');batchReveal.click('revealAll');assert.equal(batchReveal.run('s.records[0].confirmedValue'),batchReveal.run('s.current.items.reduce((sum,it)=>sum+it.value,0)'));assert.equal(batchReveal.run('s.loan.repaid'),0);batchReveal.click('sellCargo');assert.equal(batchReveal.run('s.loan.repaid'),150000);
const example=load();example.run('borrowLoan(1000000);const r={cost:1500000,revenue:2000000,confirmedValue:2000000,profitRepaymentBase:0};');assert.equal(example.run('settleLoanSale(2000000,r).cash'),1850000);assert.equal(example.run('s.loan.repaid'),150000);
const cap=fixture(500001);cap.run('s.loan.balance=100;s.loan.repaid=999900;');cap.click('sellAllStock');assert.equal(cap.run('s.loan.balance'),0);assert.equal(cap.run('s.loan.repaid'),1000000);assert.equal(cap.run('s.loan.remainder'),0);assert(cap.run('borrowLoan(6000000)'));cap.run('confirmCargoProfit(s.current)');assert.equal(cap.run('s.loan.repaid'),0);
const noDebt=fixture(500001);noDebt.run('s.loan=freshLoan();');noDebt.click('sellAllStock');assert.equal(noDebt.run('s.cash'),4000000+noDebt.run('s.records[0].revenue'));assert(noDebt.run('borrowLoan(1000000)'));noDebt.run('confirmCargoProfit(s.current)');assert.equal(noDebt.run('s.loan.repaid'),0);
const unknown=load();unknown.run('borrowLoan(1000000)');assert.equal(unknown.run('settleLoanSale(2000000,null).repaid'),0);
const old=fixture(500001);old.click('sellAllStock');old.run('persist()');const legacy=JSON.parse(old.saved.get('harbor-grid-screenshot-v2'));delete legacy.loanRuleRevision;for(const r of legacy.records){delete r.profitRepaymentBase;delete r.confirmedValue;}old.saved.set('harbor-grid-screenshot-v2',JSON.stringify(legacy));const migrated=load(old.saved);assert.equal(migrated.run('s.cash'),legacy.cash);assert.equal(migrated.run('s.loan.balance'),legacy.loan.balance);migrated.run('confirmCargoProfit(s.current)');assert.equal(migrated.run('s.cash'),legacy.cash);assert.equal(migrated.run('s.loan.balance'),legacy.loan.balance);
const reset=load();reset.run('borrowLoan(6000000)');reset.click('confirmReset');assert.equal(reset.run('s.cash'),3000000);assert.equal(reset.run('s.loan.balance'),0);
assert.deepStrictEqual(JSON.parse(reset.run('JSON.stringify(cargoTypes.map(t=>t.count))')),[11,14,17,18,24,30,50]);
console.log(JSON.stringify({repaymentPercent:30,basis:'only confirmed, realized per-box net profit after recovering cost',salePaths:outcomes,checks:'loss, exact break-even, profitable sales, fractional carry, partial sales, early-sale deferred confirmation, reveal-all, debt cap, no-debt history, idempotency, migration and reset passed'},null,2));
